title: Nicole Zattarin
logo: /assets/img/img.png
description: Quant Dev @ XSOR Capital
twitter_username: zattacole
github_username:  nicolezattarin
email: nicole.zattarin@gmail.com
theme: jekyll-theme-minimal
